---
- name: Install Cribl LogStream Master
  hosts: master

  tasks:
  - name: Ensure git package is installed
    package:
     name: git
     state: present

  - name: Ensure "cribl" user exists
    become: yes
    user:
      name: cribl
      comment: Cribl LogStream

  - name: Download and decompress LogStream bits
    become: yes
    unarchive:
      src: "{{ lookup('url', 'https://cdn.cribl.io/dl/latest') }}"
      dest: /opt
      mode: 0755
      remote_src: yes
      owner: cribl
      group: cribl
      creates: /opt/cribl

  - name: Enable LogStream boot start with systemd and ignore error if already set up
    become: yes
    expect:
      command: /opt/cribl/bin/cribl boot-start enable -m systemd -u cribl
      responses: 
        (.*)replace it with a new one(.*): "n"

  - name: Start LogStream using systemd "sudo systemctl start cribl.service"
    become: yes
    ansible.builtin.systemd:
      state: started
      name: cribl
      
