#1234567890123456789012345678901234567890123456789012345678901234567890123456789
#
# We recommend instead of running this playbook, to run the curl command as the 
# cribl user on the worker to install directly from the command line.
# 
# $ sudo curl 'http://<master-ip-or-hostname>:9000/init/install-worker.sh?token=criblmaster' | sudo sh -
# 
# this playbook works, however, it might hang, and hide errors while hanging. 
# easier to just run the command above in some other sort of script pushed out to 
# the workers if you have a lot of workers.
# 
# Assumption: you have already change the mode on the master to Mode: master, 
# and ports 4200, 9000 are open between the master and worker
# ---
# this file references a host named worker, already referenced in the sample 
# hosts file provided for this example
# 
---
- name: Bootstrap LogStream Worker
  hosts: worker
  gather_facts: False
  vars:
    https: False
    master: "<master-ip-here>"
    master_port: "9000"
    token: "criblmaster"
    worker_group: "default"

  tasks:
  - name: Download Bootstrap script
    become: true
    get_url:
      url: "http{{ (https) | ternary('s', '') }}://{{ master }}:{{ master_port }}/init/install-w
orker.sh?token={{ token }}&group={{ worker_group }}"
      dest: /tmp/install-worker.sh
      mode: u+rwx

  - name: Run installer
    become: yes
    shell:
      /tmp/install-worker.sh

  - name: Remove temp file
    file:
      path: /tmp/install-worker.sh
      state: absent
